### ISSUE TITLE
Design Logo 

### ISSUE THREAD

**Issue by mohitkh7** [mohitkh7/Easy-Learning#13]
Design logo for easy learning project. This logo will be used in navbar, email template, favicon and multiple other places.
A logo can be:
- Something reflecting learning
- Combination of letter `E` and `L`
This are just suggestion from my end. You are free to use your own creativity.

Create a png file of 1:1 ratio of logo and upload it in root directory of project.

**Comment by Sai-Adarsh** [comment]
I'm interested

**Comment by mohitkh7** [comment]
@Sai-Adarsh you can work on this issue.

**Comment by Sai-Adarsh** [comment]
> @Sai-Adarsh you can work on this issue.

![image](https://user-images.githubusercontent.com/21096774/49757831-6231b280-fce3-11e8-93c1-6900e4d82feb.png)
is this okay ?

**Comment by mohitkh7** [comment]
- Rather than having a circle what if we have a Sqaure like shape in background ?
- Letter E&L are not looking impressive. Try either changing font or spacing between them.

**Comment by Sai-Adarsh** [comment]
> * Rather than having a circle what if we have a Sqaure like shape in background ?
> * Letter E&L are not looking impressive. Try either changing font or spacing between them.

![image](https://user-images.githubusercontent.com/21096774/49758781-da00dc80-fce5-11e8-8463-5b17fb079c25.png)
@mohitkh7 do you like this ?

**Comment by mohitkh7** [comment]
Looks Awesome ;)

**Comment by Sai-Adarsh** [comment]
@mohitkh7 gave PR

**Comment by mohitkh7** [comment]
Resolved in #18
