### ISSUE TITLE
Remove redundant print statements from view.py file

### ISSUE THREAD

**Issue by mohitkh7** [mohitkh7/Easy-Learning#16]
Inside `learn/views.py` there are mutliple redundant print statement. Some of them are commented out and some are part of code. They were written earlier during development for debugging purpose but now they are not required.
Remove all print statements from `views.py` file

**Comment by Sai-Adarsh** [comment]
> Inside `learn/views.py` there are mutliple redundant print statement. Some of them are commented out and some are part of code. They were written earlier during development for debugging purpose but now they are not required.
> Remove all print statements from `views.py` file

shall i work in this ?

**Comment by mohitkh7** [comment]
Yes.

**Comment by mohitkh7** [comment]
Fixed in #17
