### ISSUE TITLE
Create Favicon for the project

### ISSUE THREAD

**Issue by mohitkh7** [mohitkh7/Easy-Learning#22]
Create a favicon image from `logo.png` file available in root directory. Include it as a favicon image for the project. 
How to approach:
- Generate favicon image from `logo.png` using https://www.favicon-generator.org/ or any other online service.
- Include this newly generated file as favicon by updating `base.html`. Ref: [Adding Favicon - Stackoverflow](https://stackoverflow.com/questions/9943771/adding-a-favicon-to-a-static-html-page)

**Comment by imskr** [comment]
i want to work on it

**Comment by mohitkh7** [comment]
assigned to you.

**Comment by imskr** [comment]
@mohitkh7 Please review it!  I've generated PR.

**Comment by mohitkh7** [comment]
resolved in #29
