### ISSUE TITLE
Make models.py file pep8 standard compliant

### ISSUE THREAD

**Issue by mohitkh7** [mohitkh7/Easy-Learning#23]
`learn/models.py` file is not as per pep8 guidelines. There are lots of invalid indentation and spacing. Make this file compliant to pep8 standard.

- Install pycodestyle using `pip install pycodestyle`
- run this command against `models.py` file, it will list down all the errors.
- make necessary changes to `models.py` file.
- add pycodestyle to requirements.txt

**Comment by imskr** [comment]
Done & created PR

**Comment by mohitkh7** [comment]
fixed in #28
