### ISSUE TITLE
Hide Password Guidelines

### ISSUE THREAD

**Issue by mohitkh7** [mohitkh7/Easy-Learning#4]
While Creating new account or changing password password guidelines appears. It should be made either hidden or more interactive.

**Comment by dewangmodi** [comment]
Can I work on this issue?

**Comment by mohitkh7** [comment]
Yes. You can work on it.
Assigned to you.

**Comment by dewangmodi** [comment]
anything else needs to be done on this issue?

**Comment by mohitkh7** [comment]
can we make it more interactive. Like this help text  appears only when user is typing password.
